import { createContext, useContext } from 'react';

export type Language = 'en' | 'es';
export type Theme = 'light' | 'dark';

export const translations = {
  en: {
    overview: 'Overview', habits: 'Listening habits', model: 'Data model', pipeline: 'Pipeline', docs: 'Technical docs',
    beta: 'Spotify data product / beta', heroTitle: 'Listening history, treated as an analytical system.', heroText: 'A browser-native case study that turns a Python ETL pipeline, a star schema and Parquet into a clear, interactive view of listening behavior.', explore: 'Explore the data', seePipeline: 'See the pipeline', path: 'The path to an insight',
    currentDataset: 'Current dataset', queryable: 'What the pipeline makes queryable', queryableText: 'These figures are calculated in the browser from the processed fact and dimension tables. They are not hardcoded presentation metrics.', technicalBeta: 'A technical beta', inspectModel: 'Inspect the model behind the visual layer.', inspectText: 'Every chart is backed by a predefined SQL query executed by DuckDB WASM. The interface keeps the analytical architecture close to the surface.', openModel: 'Open the data model',
    events: 'Events', listeningTime: 'Listening time', tracks: 'Unique tracks', artists: 'Artists', years: 'Observed years', rowsFact: 'Rows in the fact table', derivedMs: 'Derived from ms_played', excludesUnknown: 'Excludes unknown keys', distinctArtists: 'Distinct track artists', hourlyDimension: 'Hourly date dimension',
    interactive: 'Interactive analysis', findShape: 'Find the shape of listening.', exploreText: 'Explore event volume, time spent and recurring behavior across the dimensional model.', localQuery: 'DuckDB WASM / local query', exploreSlice: 'Explore slice', filterModel: 'Filter the analytical model', year: 'Year', device: 'Device', allYears: 'All years', allDevices: 'All devices',
    analysis: 'Analysis', viewSql: 'View SQL', noData: 'No data for the current filters.', querying: 'Querying Parquet through DuckDB…', unavailable: 'Query unavailable.',
    timeOverYears: 'Listening time over years', timeOverYearsText: 'Hours derived from the event-level ms_played measure.', topArtists: 'Top artists by events', topArtistsText: 'The most frequent artist values in the track dimension.', topArtistsTime: 'Top artists by listening time', topArtistsTimeText: 'Artists ranked by total ms_played, not event count.', rhythm: 'Listening rhythm', rhythmText: 'Event density by weekday and hour of day.', topTracks: 'Top tracks', topTracksText: 'Ranked by event count, with unknown track keys removed.', deviceProfile: 'Device behavior', deviceProfileText: 'Events, time and average duration by device. The selected device never hides the comparison.', geography: 'Geographic footprint', geographyText: 'Aggregated countries only. Raw IP addresses never reach the UI.', cities: 'Top cities', citiesText: 'Aggregated city values from the enriched location dimension.',
    peakHour: 'Peak hour', activeWeekday: 'Most active weekday', averageEvent: 'Average event', skipRate: 'Skip rate', shuffleRate: 'Shuffle usage', eventsAt: 'events', minutes: 'min / event',
    quality: 'Data quality', unknownTracks: 'Unknown tracks', unknownLocations: 'Unknown locations', trackCoverage: 'Track mapping', locationCoverage: 'Location enrichment',
    modelKicker: 'Analytical model', modelTitle: 'A star schema designed for questions.', modelText: 'The frontend does not flatten the data into a presentation export. It joins the fact table to its dimensions at query time.', factDescription: 'One row per recorded listening event.', joins: 'joins via surrogate key', privacy: 'Privacy boundary', privacyText: 'The enriched location table contains IP data for analytical joins, but the frontend projects only aggregated country values.', timeDimension: 'Time at hourly granularity', trackDimension: 'Track, artist and album attributes', deviceDimension: 'Platform classification', episodeDimension: 'Podcast context', locationDimension: 'Country-level geographic enrichment',
    pipelineKicker: 'Pipeline anatomy', pipelineTitle: 'From raw history to an insight.', pipelineText: 'The beta makes the full route legible: Python owns transformation, DuckDB owns browser-side querying, and React owns interpretation.', rawStep: 'Raw listening-history exports enter the configured input directory.', validationStep: 'The orchestrator checks input, output and log paths before ETL.', cleanStep: 'JSON is concatenated, timestamps are parsed and unused audiobook columns are removed.', transformStep: 'Dimensions receive keys; the fact table receives foreign-key references.', parquetStep: 'Seven analytical files become a compact, columnar contract for BI tools.', geoStep: 'Location attributes are enriched when the shared databases are available.', browserStep: 'DuckDB WASM runs predefined SQL over Parquet; ECharts renders the result.', fatal: 'Fatal', fatalText: 'Core ETL errors stop the run and are logged with context.', recoverable: 'Recoverable', recoverableText: 'GeoIP and reporting failures warn, allowing the core outputs to remain usable.',
    discovery: 'Music discovery', discoveryText: 'How the library expands and how concentrated the listening is.', topTrack: 'Most listened track', topAlbum: 'Most listened album', uniqueAlbums: 'Unique albums', diversity: 'Music diversity', newArtists: 'New artists', newTracks: 'New tracks', newAlbums: 'New albums', growthText: 'First observed year in this filtered slice.', consistency: 'Listening consistency', consistencyText: 'Daily activity, listening concentration and consecutive-day behavior.', peakDay: 'Best listening day', peakMonth: 'Best listening month', activeDays: 'Active days', inactiveDays: 'Inactive days', maxStreak: 'Longest streak', artistExplorer: 'Explore all artists', artistExplorerText: 'The chart shows the leading artists. The table contains every result for this slice.', searchArtists: 'Search artists', showTable: 'Explore full table', hideTable: 'Hide full table', rank: 'Rank', hours: 'Hours',
    language: 'Language', english: 'English', spanish: 'Español', darkMode: 'Use dark mode', lightMode: 'Use light mode', footer: 'Spotify listening data / analytical frontend beta', stack: 'Python ETL · Parquet · DuckDB WASM · ECharts',
  },
  es: {
    overview: 'Resumen', habits: 'Hábitos de escucha', model: 'Modelo de datos', pipeline: 'Pipeline', docs: 'Documentación técnica',
    beta: 'Producto de datos Spotify / beta', heroTitle: 'El historial de escucha, tratado como un sistema analítico.', heroText: 'Un caso de estudio en el navegador que convierte un pipeline ETL de Python, un esquema estrella y Parquet en una vista interactiva del comportamiento de escucha.', explore: 'Explorar los datos', seePipeline: 'Ver el pipeline', path: 'El camino hacia un insight',
    currentDataset: 'Dataset actual', queryable: 'Lo que el pipeline hace consultable', queryableText: 'Estas cifras se calculan en el navegador desde la tabla de hechos y sus dimensiones. No son métricas hardcodeadas.', technicalBeta: 'Una beta técnica', inspectModel: 'Inspecciona el modelo detrás de la capa visual.', inspectText: 'Cada gráfico usa una consulta SQL predefinida ejecutada por DuckDB WASM. La interfaz mantiene visible la arquitectura analítica.', openModel: 'Abrir el modelo de datos',
    events: 'Eventos', listeningTime: 'Tiempo de escucha', tracks: 'Tracks únicos', artists: 'Artistas', years: 'Años observados', rowsFact: 'Filas en la tabla de hechos', derivedMs: 'Derivado de ms_played', excludesUnknown: 'Excluye claves desconocidas', distinctArtists: 'Artistas distintos', hourlyDimension: 'Dimensión temporal horaria',
    interactive: 'Análisis interactivo', findShape: 'Encuentra la forma de la escucha.', exploreText: 'Explora el volumen de eventos, el tiempo y los patrones recurrentes del modelo dimensional.', localQuery: 'DuckDB WASM / consulta local', exploreSlice: 'Explorar segmento', filterModel: 'Filtrar el modelo analítico', year: 'Año', device: 'Dispositivo', allYears: 'Todos los años', allDevices: 'Todos los dispositivos',
    analysis: 'Análisis', viewSql: 'Ver SQL', noData: 'No hay datos para estos filtros.', querying: 'Consultando Parquet con DuckDB…', unavailable: 'Consulta no disponible.',
    timeOverYears: 'Tiempo de escucha por año', timeOverYearsText: 'Horas derivadas de la medida ms_played por evento.', topArtists: 'Artistas principales por eventos', topArtistsText: 'Los valores de artista más frecuentes en la dimensión de tracks.', topArtistsTime: 'Artistas principales por tiempo', topArtistsTimeText: 'Artistas ordenados por ms_played total, no por cantidad de eventos.', rhythm: 'Ritmo de escucha', rhythmText: 'Densidad de eventos por día de la semana y hora.', topTracks: 'Tracks principales', topTracksText: 'Ordenados por eventos, excluyendo claves de track desconocidas.', deviceProfile: 'Comportamiento por dispositivo', deviceProfileText: 'Eventos, tiempo y duración media por dispositivo. El dispositivo seleccionado no oculta la comparación.', geography: 'Huella geográfica', geographyText: 'Solo países agregados. Las IP nunca llegan a la interfaz.', cities: 'Ciudades principales', citiesText: 'Valores de ciudad agregados desde la dimensión de ubicación enriquecida.',
    peakHour: 'Hora pico', activeWeekday: 'Día más activo', averageEvent: 'Evento promedio', skipRate: 'Tasa de saltos', shuffleRate: 'Uso de aleatorio', eventsAt: 'eventos', minutes: 'min / evento',
    quality: 'Calidad de datos', unknownTracks: 'Tracks desconocidos', unknownLocations: 'Ubicaciones desconocidas', trackCoverage: 'Mapeo de tracks', locationCoverage: 'Enriquecimiento geográfico',
    modelKicker: 'Modelo analítico', modelTitle: 'Un esquema estrella diseñado para preguntas.', modelText: 'El frontend no aplana los datos en un export de presentación. Une la tabla de hechos con sus dimensiones en tiempo de consulta.', factDescription: 'Una fila por evento de escucha registrado.', joins: 'une mediante clave sustituta', privacy: 'Límite de privacidad', privacyText: 'La dimensión enriquecida contiene IP para los joins analíticos, pero el frontend solo proyecta países agregados.', timeDimension: 'Tiempo con granularidad horaria', trackDimension: 'Atributos de track, artista y álbum', deviceDimension: 'Clasificación de plataforma', episodeDimension: 'Contexto de podcasts', locationDimension: 'Enriquecimiento geográfico por país',
    pipelineKicker: 'Anatomía del pipeline', pipelineTitle: 'Del historial bruto al insight.', pipelineText: 'La beta hace visible el recorrido: Python transforma, DuckDB consulta en el navegador y React interpreta.', rawStep: 'Los historiales JSON entran en el directorio configurado.', validationStep: 'El orquestador comprueba las rutas de entrada, salida y logs antes del ETL.', cleanStep: 'Se concatenan JSON, se parsean timestamps y se eliminan columnas de audiobooks sin datos.', transformStep: 'Las dimensiones reciben claves y la tabla de hechos referencias foráneas.', parquetStep: 'Siete archivos analíticos forman un contrato columnar para herramientas BI.', geoStep: 'Las ubicaciones se enriquecen si las bases compartidas están disponibles.', browserStep: 'DuckDB WASM ejecuta SQL predefinido sobre Parquet y ECharts muestra el resultado.', fatal: 'Fatal', fatalText: 'Los errores del ETL principal detienen la ejecución y se registran con contexto.', recoverable: 'Recuperable', recoverableText: 'Los errores de GeoIP y reportes generan avisos, pero mantienen utilizables las salidas principales.',
    discovery: 'Descubrimiento musical', discoveryText: 'Cómo crece la biblioteca y qué tan concentrada está la escucha.', topTrack: 'Canción más escuchada', topAlbum: 'Álbum más escuchado', uniqueAlbums: 'Álbumes únicos', diversity: 'Diversidad musical', newArtists: 'Artistas nuevos', newTracks: 'Tracks nuevos', newAlbums: 'Álbumes nuevos', growthText: 'Primer año observado en este segmento filtrado.', consistency: 'Constancia de escucha', consistencyText: 'Actividad diaria, concentración del tiempo y comportamiento consecutivo.', peakDay: 'Día con más escucha', peakMonth: 'Mes con más escucha', activeDays: 'Días activos', inactiveDays: 'Días sin escucha', maxStreak: 'Racha máxima', artistExplorer: 'Explorar todos los artistas', artistExplorerText: 'El gráfico muestra los artistas líderes. La tabla contiene todos los resultados del segmento.', searchArtists: 'Buscar artistas', showTable: 'Explorar tabla completa', hideTable: 'Ocultar tabla completa', rank: 'Posición', hours: 'Horas',
    language: 'Idioma', english: 'English', spanish: 'Español', darkMode: 'Usar modo oscuro', lightMode: 'Usar modo claro', footer: 'Datos de escucha Spotify / frontend analítico beta', stack: 'ETL Python · Parquet · DuckDB WASM · ECharts',
  },
} as const;

export type CopyKey = keyof typeof translations.en;
export const LanguageContext = createContext<{ language: Language; setLanguage: (language: Language) => void }>({ language: 'en', setLanguage: () => undefined });
export const useLanguage = () => useContext(LanguageContext);
export const ThemeContext = createContext<{ theme: Theme; setTheme: (theme: Theme) => void }>({ theme: 'light', setTheme: () => undefined });
export const useTheme = () => useContext(ThemeContext);
